sequenceDiagram
    autonumber
    participant C as Customer
    participant Mu as MultiSafepay
    participant Me as Merchant

    C->>Mu: Selects bank transfer at checkout
    alt Redirect flow
    Mu->>C: Redirects to payment page to confirm <br> their bank account number and (optionally) bank country, <br> then displays payment instructions
    else Direct flow
    Mu->>C: Redirects to your success page, <br> then emails payment instructions <br> (or email the instructions yourself)
    end
    C->>Mu: Transfers funds (online or with teller) <br> (takes 1–3 business days) 
    Mu->>Me: Matches payment and settles funds