sequenceDiagram
    autonumber
    participant C as Customer
    participant Mu as MultiSafepay
    participant E as Edenred
    participant Me as Merchant

    C->>Mu: Selects Edenred at checkout
    Mu->>C: Redirects to payment page <br> to select the relevant voucher, <br> then to their Edenred account
    C->>E: Authenticates account, and authorizes MultiSafepay access
    E->>Mu: Confirms authorization <br> and sufficient funds on voucher
    E->>Me: Settles funds