sequenceDiagram
    autonumber
    participant C as Customer
    participant Mu as MultiSafepay
    participant CB as Customer's bank
    participant Me as Merchant

    alt Redirect flow
    C->>Mu: Selects iDEAL (QR) at checkout
    Mu->>C: Redirects to payment page to select their bank, <br> then to online banking
    else Direct flow
    C->>Mu: Selects iDEAL (QR) and their bank at checkout
    Mu->>C: Redirects to online banking
    end
    C->>CB: Authenticates account/scans QR code and completes payment
    CB->>Mu: Transfers funds 
    Mu->>Me: Settles funds