sequenceDiagram
    autonumber
    participant C as Client-side
    participant Me as Merchant's server
    participant Mu as MultiSafepay

    C->>Me: Places order
    Me->>Mu: Requests payment page
    Mu->>Me: Returns payment page
    Me->>C: Redirects to payment page
    C->>Mu: Completes payment
    Mu->>Me: Notifies of payment updates via webhook