sequenceDiagram
    autonumber
    participant C as Customer
    participant Mu as MultiSafepay
    participant P as PayPal
    participant Me as Merchant

    C->>Mu: Selects PayPal at checkout
    alt Redirect flow
    Mu->>C: Redirects to payment page, <br> then to their PayPal account
    else Direct flow
    Mu->>C: Redirects to PayPal account
    end
    C->>P: Authenticates account, and completes payment 
    P->>Me: Settles funds in your <br> PayPal business account