sequenceDiagram
    autonumber
    participant C as Customer
    participant Mu as MultiSafepay
    participant S as Sodexo
    participant Me as Merchant

    C->>Mu: Selects Sodexo at checkout
    Mu->>C: Redirects to payment page <br> to select the relevant voucher, <br> then to their Sodexo account
    C->>S: Authenticates account, and authorizes MultiSafepay access
    S->>Mu: Confirms authorization <br> and sufficient funds on voucher
    S->>Me: Settles funds