sequenceDiagram
    autonumber
    participant C as Customer
    participant Me as Merchant
    participant Mu as MultiSafepay
    participant Zi as Zinia
    C->>Me: Selects Zinia at checkout
    Me->>Mu: Creates order <br> (direct and redirect flow supported)
     Note over Zi: Performs risk assessment 
        alt Zinia declines the order 
    Zi->>Mu: Advises that order was declined
    Mu->>Me: Advises that order was declined
    Me->>C: Advises that order was declined
    else Zinia accepts the order 
    end
    Zi->>Mu: Authorizes the payment
     Me->>C: Ships order fully or partially
      Note over Me: Manually changes the order status to Shipped.
    Zi->>Mu: Transfers funds
    Mu->>Me: Settles funds 
    loop While payment is outstanding
	    Zi->>C: Sends payment reminders
    end
    C->>Zi: Completes payment via iDEAL or bank transfer
    Zi->>C: Notifies that the order is completed
    alt Customer doesn't pay  
    Note over Zi: Sends invoice to debt collector
    end

   
   
    